In [19]:
import numpy as np
import cv2
xx=cv2.imread("1.png")
print(type(xx))
print("xx: ",xx.shape)
x=np.array([[1,2],[3,4],[5,6]])
# from the outer to inner, one data include two tensor ,and every tensor include 3 tensor, and four...
# so when it is image, we can know it is stored by rows,every sencond tensor have 1004 tensors,and have 3 in every of them.
# standfor the channels
ch=np.array([[[1,2,3,4],[3,4,5,4],[1,3,3,4]],[[1,2,3,4],[3,4,5,3],[1,3,3,5]]])
print("xx[0]: " ,xx.shape[0])
print(ch)
x.shape
ch.shape

<class 'numpy.ndarray'>
xx:  (753, 1004, 3)
xx[0]:  753
[[[1 2 3 4]
  [3 4 5 4]
  [1 3 3 4]]

 [[1 2 3 4]
  [3 4 5 3]
  [1 3 3 5]]]


(2, 3, 4)

In [9]:
y=x.reshape(2,3)
print(x.shape[0])

3


In [8]:
y.shape

(2, 3)