In [1]:
test="helloword"

In [3]:
print("test",test)

test helloword


np.exp() ---> simoid function(logistic function),non-linear function.  

$sigmoid(x) = \frac{1}{1+e^{-x}}$

In [13]:
import math
def basic_sigmoid(x):
    """
    compute sigmoid of x
    Argument:
    x-- A scalar
    Return:
    s -- sigmoid(x)
    """
    s=1/(math.exp(-x)+1)
    return s

In [14]:
basic_sigmoid(3)

0.9525741268224334

if x is  vector, it will be wrong ,for example the  below,  we need use the numpy .  
numpy can do operator onto vector

In [15]:
x=[1,2,3]
basic_sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [17]:
import numpy as np 
x=np.array([1,2,3])
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692]


In [18]:
x=np.array([1,2,3])
print(x+3)

[4 5 6]


numpy implement sigmoid

In [19]:
import numpy as np
def np_sigmoid(x):
    """
    compute sigmoid x vector
    Argument :
    x -- a vector or matrix
    return s
    s --sigmoid(x)
    """
    s=1/(np.exp(-x)+1)
    return s

In [20]:
x=np.array([1,2,3])
np_sigmoid(x)

array([ 0.73105858,  0.88079708,  0.95257413])

###  1.2- sigmoid gradient

$$sigmoid\_derivative(x) = \sigma'(x) = \sigma(x) (1 - \sigma(x))\tag{2}$$

In [21]:
def sigmoid_derivative(x):
    s=1/(np.exp(-x)+1)
    ds=s*(1-s)
    return ds

In [25]:
x=np.array([1,2,3])
print("sigmoid_derivative(x)= "+str(sigmoid_derivative(x)))
print("sigmoid_derivative(x)= ",sigmoid_derivative(x))

sigmoid_derivative(x)= [ 0.19661193  0.10499359  0.04517666]
sigmoid_derivative(x)=  [ 0.19661193  0.10499359  0.04517666]


### 1.3 reshape arrays

In [28]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape(length,height,depth)
    
    return :
    v -- a vector of shape( length*height*depth,1)
    """
    v=image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return v

In [29]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print("image2vector(image)= ",image2vector(image))

image2vector(image)=  [[ 0.67826139]
 [ 0.29380381]
 [ 0.90714982]
 [ 0.52835647]
 [ 0.4215251 ]
 [ 0.45017551]
 [ 0.92814219]
 [ 0.96677647]
 [ 0.85304703]
 [ 0.52351845]
 [ 0.19981397]
 [ 0.27417313]
 [ 0.60659855]
 [ 0.00533165]
 [ 0.10820313]
 [ 0.49978937]
 [ 0.34144279]
 [ 0.94630077]]


###  normalizing rows

In [182]:
temp=np.array([[1,2],[3,4],[5,6]])
temp_0=np.linalg.norm(temp,1,0)
print("shape0: ",temp_0.shape[0])
print(temp_0)
temp_1=np.linalg.norm(temp,1,1)
print(temp_1)
temp_result=np.linalg.norm(temp,1,1)
temp_result0=np.linalg.norm(temp[0],2)

temp_devide=np.multiply(np.array([temp_result,temp_result]).reshape(temp.shape[0],temp.shape[1]),temp)
#print(temp.shape[1])
print(temp)
#print(temp[0])
print(temp_result)
print(temp_result0)
print(temp_devide)

print(temp.shape[0])
c=np.repeat(temp_result,temp.shape[0])
print(c)
print(c.shape)
c.reshape(temp.shape[0],temp.shape[0])

shape0:  2
[  9.  12.]
[  3.   7.  11.]
[[1 2]
 [3 4]
 [5 6]]
[  3.   7.  11.]
2.2360679775
[[  3.  14.]
 [ 33.  12.]
 [ 35.  66.]]
3
[  3.   3.   3.   7.   7.   7.  11.  11.  11.]
(9,)


array([[  3.,   3.,   3.],
       [  7.,   7.,   7.],
       [ 11.,  11.,  11.]])

In [119]:
def normalizeRows(x):
    """
    normalize each row of the matrix x .
    Arguments:
    x -- A numpy matrix of shape(n,m)
    
    return :
    x--the  normalized numpy matrix.
    
    """
    x_norm=1/np.linalg.norm(x,2,1)
    x_norm_matrix=np.repeat(x_norm,x.shape[1])
    x_norm_matrix=x_norm_matrix.reshape(x.shape[0],x.shape[1])
    x=np.multiply(x,x_norm_matrix)
    return x

In [120]:
temp1=np.array([[1,2],[3,4],[5,6]])
normalizeRows(temp1)
x=np.array([
        [0,3,4],
        [1,6,4]
    ])
print("normalizerows(x): ", normalizeRows(x))


normalizerows(x):  [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


### broadcasting softmax function

In [137]:
x=np.arange(4)
xx=x.reshape(4,1)
print(x,x.shape)
print(xx,xx.shape)

[0 1 2 3] (4,)
[[0]
 [1]
 [2]
 [3]] (4, 1)


In [142]:
y=np.zeros(5)
z=np.ones((3,4))
print(y)
print(z)

[ 0.  0.  0.  0.  0.]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [143]:
#one rows and one cols, we can expand the cols to rows.shape columns.
xx+y

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.]])

In [144]:
# recomplete the above normalizeRows function.
def normalizeRows_2(x):
    x_norm=1/np.linalg.norm(x,2,1)
    y=np.zeros(x.shape[1])
    x_norm_matrix=x_norm+y
    x=multiply(x,x_norm_matrix)
    return x

In [145]:
x=np.array([
        [0,3,4],
        [1,6,4]
    ])
print("normalizerows(x): ", normalizeRows(x))

normalizerows(x):  [[ 0.          0.6         0.8       ]
 [ 0.13736056  0.82416338  0.54944226]]


In [230]:
def softmax(x):
    """
    calculate the softmax for each row of the input x
    Argument:
    x-- A numpy matrix of shape(n,m)
    returns: 
    s --a numpy matrix equal cto sorfmax of x, of shape (n,m)
    """
    x_exp=np.exp(x)
    x_sum=np.linalg.norm(x_exp,1,1)
    y=np.zeros(x_exp.shape[1])
    x_sum=x_sum.reshape(2,1)
    x_sum=1/(x_sum+y)
    #print(x_exp.shape)
    #print(x_sum.shape)
    #print(x_sum)
    s=np.multiply(x_exp,x_sum)
    return s

In [231]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " , softmax(x))

softmax(x) =  [[  9.80897665e-01   8.94462891e-04   1.79657674e-02   1.21052389e-04
    1.21052389e-04]
 [  8.78679856e-01   1.18916387e-01   8.01252314e-04   8.01252314e-04
    8.01252314e-04]]


## 2)vectorization

In [232]:
import time
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]
dot=np.dot(x1,x2)
print(dot)


278


## L1 lossfunction

$$\begin{align*} & L_1(\hat{y}, y) = \sum_{i=0}^m|y^{(i)} - \hat{y}^{(i)}| \end{align*}\tag{6}$$

In [235]:
def L1(yhat,y):
    """
    arguments:
    yhat -- vector of size m 【predict labels】
    y -- vector of size m 【true labels】
    return :
    loss -- the value of the L1 loss function 
    
    """
    loss=sum(abs(y-yhat))
    return loss
    

In [236]:
yhat=np.array([.9,0.2,0.1,.4,.9])
y=np.array([1,0,0,1,1])
print("L1",L1(yhat,y))

L1 1.1


$$\begin{align*} & L_2(\hat{y},y) = \sum_{i=0}^m(y^{(i)} - \hat{y}^{(i)})^2 \end{align*}\tag{7}$$

In [239]:
def L2(yhat,y):
    """
    Arguments:
    yhat -- predict label
    y ---true label
    
    return :
    loss -- the value of the L2 loss function
    """
    
    loss= sum(pow(yhat-y,2))
    return loss

In [240]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43


# reference:

C:\Users\mathc\Desktop\blog-master\blog-master\notes_deeplearning.ai\homework\12 神经网络和深度学习_第二周_编程作业\assignment2_1