In [6]:
import mxnet as mx
from mxnet import nd
x=nd.array([1,2,3])
print(x)
x.context


[ 1.  2.  3.]
<NDArray 3 @cpu(0)>


cpu(0)

In [7]:
a=nd.array([1,2,3],ctx=mx.gpu())
b=nd.zeros((3,2),ctx=mx.gpu())
c=nd.random.uniform(shape=(2,3),ctx=mx.gpu())
(a,b,c)

(
 [ 1.  2.  3.]
 <NDArray 3 @gpu(0)>, 
 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]
 <NDArray 3x2 @gpu(0)>, 
 [[ 0.32977498  0.43025011  0.70026755]
  [ 0.77781075  0.29912937  0.39169419]]
 <NDArray 2x3 @gpu(0)>)

In [19]:
from mxnet import gluon
net=gluon.nn.Sequential()
net.add(gluon.nn.Dense(1))
net.add(gluon.nn.Dense(1))
net.add(gluon.nn.Dense(1))
net.initialize(ctx=mx.gpu())


In [20]:
data=nd.random.uniform(shape=[3,2],ctx=mx.gpu())
net(data)


[[  1.53697636e-06]
 [  2.53448206e-07]
 [  4.58015620e-07]]
<NDArray 3x1 @gpu(0)>

In [21]:
net[0].weight.data()


[[ 0.02332029  0.04696382]]
<NDArray 1x2 @gpu(0)>

In [22]:
net[1].weight.data()


[[-0.00169877]]
<NDArray 1x1 @gpu(0)>

In [23]:
net[2].weight.data()


[[-0.01599531]]
<NDArray 1x1 @gpu(0)>